### PR TITLE
Guide: update documentation of the CLI

### PR DESCRIPTION
**Pull request by oscarlevin**
A large set of improvements to the documentation that includes almost all the features of the CLI, new instructions for installing, and improved coverage in other sections of the guide.  

This all assumes the version of the CLI is 1.0, so please wait to merge until 1.0 is released.

### CODE REVIEW

**Comment by rbeezer** [comment]
Thanks for all the updates!  Merged with only changes to commit messages, but will need to wait a bit before I do another website update.

**Comment by rbeezer** [comment]
Now live at website.  Want to post a follow-on message @pretext-announce?  if so,

1.  Send to me to re-post, or,
2.  Have me give you posting priviliges?

**Comment by oscarlevin** [comment]
I think a post to announce would be great.  I'll let you post the following (feel free to edit as you see fit).

Updated CLI documentation in guide

With the recent release of version 1.0 of the PreTeXt-CLI, the new features have been updated in the guide.  For instillation and getting started help, see https://pretextbook.org/doc/guide/html/quickstart-getting-pretext.html.  A full description of the features of the CLI can be found at https://pretextbook.org/doc/guide/html/processing-CLI.html.

Cheers,
Oscar.


Oscar Levin,  Associate Professor,
Department of Mathematical Sciences,
University of Northern Colorado,
Ross Hall 2040D; (970) 351-2380
Schedule Student Hours: https://bit.ly/bookoscar
Zoom: https://unco.zoom.us/my/oscarlevin

**Comment by rbeezer** [comment]
> feel free to edit as you see fit

And I added an announcement of the **CLI Quickref**!!!  ;-)

**Pull request closed without merging**
