### PR TITLE
add directory information to images section of guide

### PR DESCRIPTION
**Pull request by pearcej**
fix issue #1832

### CODE REVIEW

**Comment by rbeezer** [comment]
Thanks, @pearcej!  I'll merge this, but it'll be a few days before I can get to it

**Comment by pearcej** [comment]
Thanks, @rbeezer. No rush--enjoy your vacation!

**Comment by pearcej** [comment]
@rbeezer sounds good!

**Comment by rbeezer** [comment]
> it'll be a few days before I can get to it

A few months?  Sorry!  This did come in right at the start of a long trip, but that is not a good excuse for losing track of it.  I'm usually better about making PRs a priority.  Keep 'em coming!

Consolidated, rebased, added onto commit message, but no changes in content.  You'll need to trash your own branch on your end.  Website version will update sometime very soon (but not right now).

Thanks!

**Comment by pearcej** [comment]
Thanks, Rob!

**Pull request closed without merging**
