### PR TITLE
WeBWorK: move Activate button

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This PR is for discussion, until some details can be worked out. I'll start a discussion thread now and reference this PR.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Force pushed this following a rebase over master and resolving a conflict.

**Comment by rbeezer** [comment]
Is this ready, then?  Do you want it now, or still need a pause?

**Comment by Alex-Jordan** [comment]
No, this is not good for at least two reasons.
* Having the button off to the side doesn't work well with narrow situations like two-column or phone.
* When for example Runestone renders an exercise independently, outside of the actual book, it does not get the pretext_add_on CSS applied and then this button is really bad.

So more experimentation/research is needed.

**Comment by bnmnetp** [comment]
Alex,

I can include the required CSS **if** I know about it.  The reason I hadn't included it recently was because I've not had to add CSS from PreTeXt or WebWork on the assignment page in the past.   If it makes sense to to do that I'm perfectly happy to do so.

**Pull request closed without merging**
