### PR TITLE
Partial Order Parsons Implemented & Documented

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Implementation of markup for Parsons problems to allow for partial order autograding.

### CODE REVIEW

**Comment by rbeezer** [comment]
How do you feel about using `@name` where you have used `@tag`?  Totally cosmetic, but important for authors' efficiency/sanity?  We have a `<tag>` element (to make consistent documentation of PreTeXt itself) and `@name` gets used many other places, sometimes in a very similar way.  It'd help authors be more likely to "guess" the right attribute name.

**Comment by ascholerChemeketa** [comment]
That makes sense.

Change made and documentation typo fixed.

**Comment by rbeezer** [comment]
Consolidated and merged.

A `cline` in the block named `a` had markup (`nbsp`) which was washed away in HTML, appeared in PDF, and raised a warning during processing (no makup allowed in `cline`).  So I made an executive decision to remove it.  Holler if that was wrong.

Thanks for getting to this - I never finished my attempt.

**Comment by ascholerChemeketa** [comment]
@rbeezer That was the correct decision. I believe that was an artifact I introduced while trying to help Kevin figure out how to force an empty line into the Parsons block. My apologies!

**Comment by rbeezer** [comment]
>  My apologies!

No problem.  That's why we do reeviews.  Glad it was handled smoothly.

**Pull request closed without merging**
