### PR TITLE
untested attempt for interactive preview logic, assuming a single local HTML file with all interactives

### PR DESCRIPTION
**Pull request by StevenClontz**
For @rbeezer consideration.

### CODE REVIEW

**Comment by rbeezer** [comment]
Yes, that seems workable.  There will need to be a core `xsltproc()` call to apply the stylesheet I'm working on to the source, with output into a temporary directory full of iframe content files and support files (JS scripts, etc).  We can give the HTML file of interactives (fed into snapshotting) a predictable name, say `interactives.html`.

I suspect that the Python routine can use a small amout of `lxml` to simply identify the`iframe/@id` for the things to snapshot.  In other words, the present `extract-interactives.xsl` stylesheet can be retired and its output not consulted.

**Comment by StevenClontz** [comment]
Agreed on retiring `extract-interactives.xsl` (and I suspect most `extract-` sheets could be similarly retired at some point.)

**Comment by rbeezer** [comment]
@dbrianwalton is well down the road on this one, with preliminary work at #1894, #1895, and more to come.

So I'm going to close this.  Thanks, @StevenClontz, for promoting this approach.

**Comment by StevenClontz** [comment]
Thanks @dbrianwalton !

**Pull request closed without merging**
