### PR TITLE
Schema says statement is not mandatory in an exercise....

### PR DESCRIPTION
**Pull request by jjrsylvestre**
but basics guide says otherwise.

Also changed some `<c>` tags to `<tag>` tags.

### CODE REVIEW

**Comment by mitchkeller** [comment]
Good catch. I would suggest adding some index entries for hint/answer/solution in exercisegroup.ptx to mirror what is already there for `statement`.

I have mixed feelings about removing the `statement` tags from the other `exercise` tags in exercisegroup.ptx. I imagine the unfortunate situation where someone copies and pastes this, puts their content in it, and then remembers that they can add `hint` and tries to put `hint` after the final `p`. At best, they have invalid PTX. At worst, they get mangled output. I don't see much cost to having template code that has the `statement` tag in there even when not strictly necessary, since I'd say it's a best practice to author with `statement` tags in there even without any hint/answer/solution.

**Comment by davidfarmer** [comment]
I have always been against tags that can be inferred by a mechanical 
process.  I understand that we have them because it makes it easier
to write the xsl, but it would be nice to decide that, in principle,
it is desirable to make those tags optional.

I suggest that 'statement' is an example.  When a definition, theorem,
or exercise only contains a statement, then there is no logical need
for the 'statement' tag.

But what if there is a hint, answer, or solution?  As long as those
are required to come after the statement, then one can infer that
the statement is everything up to the first hint, answer, or solution.

Is there some situation I am missing?

**Comment by jjrsylvestre** [comment]
Actually, looking at the output, all the new idx's muddy things up.

Should any of the code snippets have idx at all in them? (Other than demonstrating the use of the <idx> tag, of course.)

Probably should just put any useful idx in as child of the <program> or <listing> that contains the code snippet. You want code snippets that are easy to copy-and-paste-and-use, not snippets that require copy-and-paste-and-delete-a-bunch-of-crap-and-use.

**Comment by rbeezer** [comment]
Finally!  Discussion here gave me pause.  A long pause.  I'm happy with what is here now, as reflecting best advice **given current XSL implementation**.  If we need new advice, we need (substantial) new code.  Thanks, @jjrsylvestre for your patience (and everyone's input).

**Pull request closed without merging**
