### PR TITLE
Update CLI quick start for image generation

### PR DESCRIPTION
**Pull request by kcrisman**
This image generation instructions currently lead to errors.  This should be accurate for the current state of the CLI, but edits are welcome since the precise verbiage, use of remark, etc. may not be as desired by the maintainers.

### CODE REVIEW

**Comment by kcrisman** [comment]
Comments: I don't know how to change the name of the branch using Github alone here, and I am leaving this in draft mode so nobody hurts me, but this draft is ready for merging as far as my own thoughts.  Primarily in draft to see whether @oscarlevin or others think the styling is right, or whether they have some more comprehensive stuff already on the way.

**Comment by rbeezer** [comment]
Looks fine to me, but @oscarlevin can decide the ultimate disposition.  At your service.

**Review by StevenClontz — APPROVED** [review]

**Comment by kcrisman** [comment]
I'll set it ready for review based on @StevenClontz approval (not sure what exactly that means on GH?).

**Comment by StevenClontz** [comment]
It means nothing other than I "approve" it, though it's possible on GitHub to require N approving reviews before merging a PR.

**Comment by oscarlevin** [comment]
I'm in the middle of fixing this section as well as the more comprehensive cli page, so some of this will be rewriten.  But I like your language better than mine, so I would recommend merging now.

**Comment by rbeezer** [comment]
Thanks, everyone, especially KDC.

*  Had to fix an unbalanced `c` element after a `p`, which should have gone after an `xi:include` example.  Just merged that into current commit.
*  Pushed, so @oscarlevin can proceed, but have not yet rebuilt website version (maybe tonight?)

**Pull request closed without merging**
