### PR TITLE
Limited lifespan for element deprecation warnings

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
The deprecation warnings are expensive to process in a large book. For many authors, checking 10-year-old warnings is moot. But for a long-neglected book, doing so might be important.

This modifies the deprecation-message calls to only process the source if the warning is less than some `max-age`

Currently `max-age` defaults to 5. There is a new stringparam `author.deprecations.max-age` that can be used to set something different - either `none` or an integer number of years worth of checks to run.

Build time for sample book with different `max-age` values:
```
no max      : 30 seconds
5 years     : 22 seconds
2 years     : 18 seconds
0 years     : 16 seconds
```

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
@rbeezer If you like the approach, and do want the really old deprecations. I'll go pull them out of history and add them back in a new commit. It looks like they are in a mix of formats, so I won't do that unless you say "go".

**Comment by rbeezer** [comment]
Reviewing on fone.  How about giving an author only two choices: "recent" and "all"?  We can't make it too easy to squelch these and then pay the price with difficult support questions.

**Comment by rbeezer** [comment]
I can't immediately see the reason for `dyn:evaluate`.  I should be at Drop-In in a bit.

**Comment by ascholerChemeketa** [comment]
Force pushed with changes discussed in Drop in. stringparam now only offers a boolean choice between current warnings or all warnings.

**Comment by rbeezer** [comment]
Fantastic!  Added a little follow-on commit to error-check the parameter.

Several messages coming on `-dev`.  Thanks.

**Pull request closed without merging**
