### PR TITLE
attempt to get codespaces working with core pretext repo

### PR DESCRIPTION
**Pull request by StevenClontz**

### CODE REVIEW

**Comment by StevenClontz** [comment]
@oscarlevin 

Try opening this commit in a codespace. For whatever reason, PreTeXt-tools isn't finding the targets.

**Comment by oscarlevin** [comment]
That's because your pretext.ptx has two targets without a publication file.  The way I hacked this to work with the CLI is that the CLI has a `-t` option that prints a list of targets, and that gets read by pretext-tools.  But for some reason the CLI is looking for a entry for `<publication>` in the manifest (maybe to make sure it really is a manifest??), and there is an error when it doesn't find it.  Obviously, I should work to fix that in the CLI, to at least make the failure more graceful

**Comment by StevenClontz** [comment]
Feel free to close, I will redo this in a fresh PR.

**Comment by oscarlevin** [comment]
Just FYI, the issue wasn't that there were no publication files, it was that `project.ptx` didn't have a `<publication>` element for at least one target.  See #1872 and https://github.com/PreTeXtBook/pretext-cli/issues/424

**Pull request closed without merging**
