### PR TITLE
No footnotes in footnotes, even for URLs

### PR DESCRIPTION
**Pull request by kcrisman**
We were still creating footnotes for URLs located in footnotes.  These commits fix that problem, and provide light guidance for alternate strategy.

### CODE REVIEW

**Comment by rbeezer** [comment]
Very good, and documentation is perfect.  Merged, and will update website in due course.

Mild editing of commit messages, even if one is slightly inaccurate.  ;-)

THANKS!

**Comment by kcrisman** [comment]
>
> Mild editing of commit messages, even if one is slightly inaccurate. ;-)
>
> THANKS!
>
> Inaccurate - because I didn't include the data URLs?  I'm thanking you
too, because I really need this.

**Comment by rbeezer** [comment]
> Inaccurate - because I didn't include the data URLs? 

NO!  I said "Guide:" and it is a bit more than that...

**Comment by kcrisman** [comment]
>
>
> NO! I said "Guide:" and it is a bit more than that...
>
 Haha, I see!  Speaking of which, now I have to go update all my URLs in
footnotes to follow my own advice.

**Pull request closed without merging**
