### PR TITLE
Native search improvement

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Moves search input into the results panel and searches on type
Adds results snippets & highlighting
Stores search query between searches

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
These three PR's must be sync'd:
https://github.com/PreTeXtBook/pretext/pull/2057
https://github.com/PreTeXtBook/CSS_core/pull/69
https://github.com/PreTeXtBook/JS_core/pull/56

**Comment by ascholerChemeketa** [comment]
Live demos for default and reference style searches:
https://computerscience.chemeketa.edu/ascholer/pretext-test/search/html/default/sets-sage.html
https://computerscience.chemeketa.edu/ascholer/pretext-test/search/html/reference/sets-sage.html

**Comment by davidfarmer** [comment]
I am guessing we need to chanve the JavaScript version?

**Comment by ascholerChemeketa** [comment]
I just pushed a commit that should make this backwards compatible. I am successfully using a book that does not have the PR with the new code.

But the new code won't be pointless without the pretext/css PR. 

Not sure what that means re: versioning.

**Comment by davidfarmer** [comment]
I have merged the CSS and JS changes, and made a separate PTX pull request
incrementing the CSS and JS versions.  So this can be accepted after my pull
request (or just delete my pull request and make those changes in another way: move CSS from 0.8 to 0.81 and JS from 0.3 to 0.31 .

**Comment by ascholerChemeketa** [comment]
@rbeezer Tracked down why search result snippets are not appearing in the test version.

The last commit in this PR (https://github.com/PreTeXtBook/pretext/pull/2057/commits/29b38ec92410419467e77204c32bd5b8449e50da) should have made a change to lunr-pretext-search-index.js when you rebuilt.

But the test version of the file (https://pretextbook.org/beta/search-focused-css-2023-09-06/lunr-pretext-search-index.js) does not have the changes. There should be a line `this.metadataWhitelist = ['position']` at the end after `this.field('body')`

Either that file did not get rebuilt/updated or something else happened. Can you rebuild the test and check lunr-pretext-search-index.js? Assuming it ends up with the extra line can you then upload it to the test site?

**Comment by ascholerChemeketa** [comment]
BTW - touchups to CSS are live at:
https://ascholerchemeketa.github.io/pretext_css_core/css/test-combined-fix/

If you set `html.css.server` to `https://ascholerchemeketa.github.io/pretext_css_core` and `html.css.version` to `test-combined-fix`, on the test rebuild you will be pointing at a version of the CSS with a few fixes based on the merged commits. It also gives more space for section numbers and gracefully handles obnoxiously long ones.

One more possible change to that fixup changeset based on what I hear about the user preferences menu from dev-list. Once it is all set I'll submit to pretext_css_core as a PR. It won't need a version bump.

**Comment by ascholerChemeketa** [comment]
Yes, that sounds fine.

**Comment by ascholerChemeketa** [comment]
Just added one last modification to enable cleaner CSS.

David merged the CSS tweaks needed for the merged version. Those include the extra spacing for section numbers. They cleanly support up to XX.XX. Subsections (if shown) should handle XX.XX.XX. Larger numbers push the title over:
image

**Comment by rbeezer** [comment]
Thanks, Andrew, this is great!  Website samples being updated right now, give it 20 minutes.  I'll put something on `pretext-announce`.

**Pull request closed without merging**
