### PR TITLE
Guide: Update CLI documentation for v2.0

### PR DESCRIPTION
**Pull request by oscarlevin**
A large update to the CLI sections of the guide to coincide with CLI version 2.0.  Quickref has also been updated.

Also a couple typo fixes that I came across.

### CODE REVIEW

**Comment by oscarlevin** [comment]
We are ready to announce CLI 2.0 as soon as this gets merged.

**Comment by rbeezer** [comment]
This was in the queue during a push of merging PRs the past few days, but it got delayed for a less-productive time since it has quite a few tedious whitespace errors that I was going to correct.  Biggest is some comments used for file headers getting shortened, which will disrupt using sed to update copyrights.  (Others are line endings, file ending, iirc.)

* Correct them and force-push, and I can merge sooner.
* Wait on me to get back to it, which would be later.

Thanks! -Rob

**Comment by oscarlevin** [comment]
I can definitely take care of those issues.  Must have been an autoformatter that messed with the top-of-file comments.

For the whitespace, it looks like the formatter removed existing whitespace between sentences.  Is this an issue?  Does the guide have a preferred number of spaces after a period?

**Comment by rbeezer** [comment]
Spaces after a period does not really matter.  I use more blank lines rather than fewer, but there are no guidelines.

It is trailing whitespace and "blank" lines that are not blank that are most at issue, generally.

One person adds them, then somebody else makes a PR, touches an unrelated file, their editor "fixes" these things, and poof, you've got a diff that makes no sense.  Best to be religious about not letting it in the first place.  ;-)

**Comment by oscarlevin** [comment]
Should be all better now.

**Comment by rbeezer** [comment]
30 minutes spent trying to get the fixes into the proper commits.  And then I see there is still some trailing spaces.

Can you `git reset HEAD~5`, fix whitespace, and then rebuild two or three topical commits?  I can walk you through this on Tuesday if you'd like.

**Comment by oscarlevin** [comment]
I'll close this and start over.

**Pull request closed without merging**
