### PR TITLE
Update fr-CA.xml

### PR DESCRIPTION
**Pull request by JeanSebastienTurcotte**
Added interactive exercises feedback in french

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Many of these terms will appear as the text on a button. As such, it's ideal if that text can be short. Can you imagine something short for `Générer une nouvelle version aléatoire`?  If not, it is what it is, and the button will probably break to a new line.

**Comment by sean-fitzpatrick** [comment]
It might not be perfect, but `Randomiser` would be shorter. Is it somehow misleading in French?

**Comment by Alex-Jordan** [comment]
Maybe we should look into nice icons for the buttons, and these text strings can just be their titles. So it won't matter if they are long. If `Randomiser` or something short works, great. If not, please don't let it hold this up. The long text will work, and maybe not even matter if icons come into play.

**Comment by JeanSebastienTurcotte** [comment]
I based them on what we already have in our server. You can change them if
you want. See the attached file.

Le mer. 31 août 2022, 15 h 23, Alex Jordan ***@***.***> a
écrit :

**Comment by JeanSebastienTurcotte** [comment]
Picture does not seem to go through github. I'll post it on -support at https://groups.google.com/g/pretext-support/c/pOTzg-y5X5U.

I'm fine with "Randomiser" if the longer name causes problem

**Comment by Alex-Jordan** [comment]
@rbeezer Please go ahead and merge.

**Comment by rbeezer** [comment]
Thanks, everybody.  Merged just now.  Of course, it may be a while until the CLI has it.

**Pull request closed without merging**
