### PR TITLE
Icon library and navbar cleanup

### PR DESCRIPTION
**Pull request by ascholerChemeketa**
Cleans up a few aspects of the navbar to enable future work:

- Makes runestone controls be buttons (instead of divs) to match other controls that do something on the current page.
- Gives all button-like navbar controls .icon and .name so that styling can choose to display one/other or both at different breakpoints.
- Makes the primary-navigation xsl template as simple as possible by moving component logic to subtemplates. This is to minimize the code that needs to move around in order to reorder navbar items. 

All of these changes should be invisible in the current themes except for next/prev/up/down buttons that now use unicode icons instead of < > ^. (This PR in CSS was already merged and will prevent the new icons from appearing in existing layouts https://github.com/PreTeXtBook/CSS_core/pull/63)

Before:
image

After:
image

CRC Before:
image

CRC After:
image

### CODE REVIEW

**Comment by ascholerChemeketa** [comment]
I consider this complete - the actual use of the new structure will be in future PRs.

**Comment by Alex-Jordan** [comment]
> now use unicode icons

An issue I have run into with using unicode characters for icons is that an end user's device might not have a font that carries those characters. Or the device might not know to fall back to a font that it has that carries them. I see this most often with a phone. Have you tested with an Android and an iOS device, using various browsers?

In the situations where I hit this issue, I am slowly replacing the icons with svg icons. Either from an open repository, or just drawing simple ones.

**Comment by ascholerChemeketa** [comment]
That is a great call. Will update with SVGs instead of unicode to make as
broadly compatible as possible.

Andrew Scholer (he/him/his)
Computer Science Instructor/Program Chair
Chemeketa Community College
503.589.7649
computerscience.chemeketa.edu/people/andrew-scholer/

**Comment by rbeezer** [comment]
Visual inspection, and a quick before/after both look good.

I assume this is waiting on SVG icons - that'll be a very useful improvement.  If you copy from some openly-licensed collection, please note the origin in the source so we don't have to wonder later.  Thanks.

**Comment by ascholerChemeketa** [comment]
Bringing up icon library history/future on pretext-dev mailing list. I have marked this as a draft until the icons are svg'ified.

**Comment by ascholerChemeketa** [comment]
Switched all the icons to Material Symbols after the discussion on dev list.

Samples are available here:
https://computerscience.chemeketa.edu/ascholer/pretext-test/icons/html/default/sample-book.html
https://computerscience.chemeketa.edu/ascholer/pretext-test/icons/html/crc/sample-book.html

I consider this done, but leaving as draft while open for more comment.

Needs to be synced with CSS PR:
https://github.com/PreTeXtBook/CSS_core/pull/66

**Comment by rbeezer** [comment]
Looks good based on a first pass - I'll need to clean up the reverts.  I've made a "beta" for testing https://github.com/PreTeXtBook/CSS_core/pull/66 which I'll note in a few minutes there.

**Comment by rbeezer** [comment]
Sorry for the confusion.  Merged 0.8 of the CSS which includes https://github.com/PreTeXtBook/CSS_core/pull/66

Cleaned up the reversions here and edited commit messages (including one that was longer than a single line).

Merged with a single merge commit for record-keeping.  May referesh website in just a bit, after lunch.

Thanks - great improvements!

**Pull request closed without merging**
