### PR TITLE
complete transtalion of tags to pt-BR

### PR DESCRIPTION
**Pull request by lymber**
It would be nice if other Portuguese (Brazil) native speakers could check this before merging.

### CODE REVIEW

**Comment by rbeezer** [comment]
Thanks, Alex!  You could add to the thread on `pretext-dev` to alert your fellow Brazilians?  They could just drop a note here, saying "Looks good", or offering suggestions?  Or you could just emai those three translators directly and point them here?

I'll wait on this until you tell me here that it is time to merge.

**Comment by rbeezer** [comment]
I went ahead and merged this.  Thanks!

If anybody has feedback, we can iterate with improvements.

**Comment by lymber** [comment]
Nothing to thank here, I just did a small contribution to a software
that is amazing!

I'm really a bit out of this collaborative developing tools, so I don't
know what pretext-dev is (a fork, another project... sorry for
this). I'll email them to check my suggestions.

Best, Alexandre

On Feb 10 2023, Rob Beezer wrote:
> Thanks, Alex!  You could add to the thread on `pretext-dev` to alert your fellow Brazilians?  They could just drop a note here, saying "Looks good", or offering suggestions?  Or you could just emai those three translators directly and point them here?
> 
> I'll wait on this until you tell me here that it is time to merge.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/PreTeXtBook/pretext/pull/1932#issuecomment-1426402337
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
===============================================================================
Alexandre Lymberopoulos - ***@***.***
***@***.***> - https://www.ime.usp.br/~lymber
Instituto de Matemática e Estatística - Universidade de São Paulo
===============================================================================

**Comment by lymber** [comment]
Ok, I think that my suggestions are fine, let's see what other guys
think of it.

Best, Alex

On Feb 17 2023, Rob Beezer wrote:
> I went ahead and merged this.  Thanks!
> 
> If anybody has feedback, we can iterate with improvements.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/PreTeXtBook/pretext/pull/1932#issuecomment-1435324574
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

-- 
===============================================================================
Alexandre Lymberopoulos - ***@***.***
***@***.***> - https://www.ime.usp.br/~lymber
Instituto de Matemática e Estatística - Universidade de São Paulo
===============================================================================

**Comment by rbeezer** [comment]
> I'm really a bit out of this collaborative developing tools, so I don't
know what pretext-dev

Another Google Group.  Search main "pretextbook.org" page.  Need to apply for membership, but requests are usually approved right away.

**Pull request closed without merging**
